apiVersion: v2
name: spectre
description: Kubernetes Audit Event Monitoring
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - monitoring
  - events
  - storage
home: https://github.com/moolen/spectre
sources:
  - https://github.com/moolen/spectre
maintainers:
  - name: moolen
    email: beller.moritz@googlemail.com
