apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-event-monitor.fullname" . }}
  labels:
    {{- include "k8s-event-monitor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-event-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-event-monitor.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
